# Plex Configuration File
# For documentation, please visit: https://plex.us.org

server:
  name: "Plexus"
  motd: "%servername% - Minecraft %mcversion%"
  colorize_motd: true
  sample:
    - "&cForums: https://forum.plex.us.org"

titles:
  masterbuilders: [ ]
  owners:
    - Telesphoreo

# Ban message is customized in the messages.yml file. The URL to appeal at is below.
banning:
  ban_url: "https://forum.plex.us.org"

chat:
  # Should the server use Plex's chat system? It is recommended to keep this on if you are using ranks.
  # If you are using permissions, you should turn this off and use Vault to handle prefixes with a different chat plugin
  enabled: true
  # The maximum amount of characters a player can have for their tag
  max-tag-length: 16
  # Color code for name color
  name-color: 'f'

# Settings for commands relating to Plex
commands:
  # Should Plex use a "true op" system with ranks or only permission nodes
  permissions: ranks

data:
  central:
    storage: sqlite # Use mariadb, mongodb, or sqlite here
    user: ""
    password: ""
    hostname: 127.0.0.1
    port: 27017
    db: "plex"
  side: # This is Redis, leave password blank if auth is false
    enabled: false
    auth: true
    hostname: 127.0.0.1
    port: 6379
    password: ""

# See https://plex.us.org/docs/customization/config#worlds for documentation
# These gamerules apply to all worlds on the server
global_gamerules:
  - "doWeatherCycle;true"
  - "doDaylightCycle;true"
  - "doMobSpawning;false"
  - "keepInventory;true"
  - "doFireTick;false"
  - "doMobLoot;false"
  - "mobGriefing;false"
  - "doTileDrops;false"
  - "commandBlockOutput;false"
  - "naturalRegeneration;true"
  - "announceAdvancements;false"
  - "showDeathMessages;false"
  - "sendCommandFeedback;false"

worlds:
  flatlands:
    name: "Flatlands"
    permission: "plex.world.flatlands"
    noEdit: "&cYou can't edit this world!"
    gameRules:
      # The gamerules here override the global gamerules
      - "doWeatherCycle;false"
      - "doDaylightCycle;false"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1
  adminworld:
    name: "Admin World"
    permission: "plex.world.adminworld"
    requiredLevels:
      - "Rank.ADMIN" # Minimum rank requirement
    noEdit: "&cYou can't edit this world!"
    gameRules:
      - "doWeatherCycle;false"
      - "doDaylightCycle;false"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1
  masterbuilderworld:
    name: "MasterBuilder World"
    permission: "plex.world.masterbuilderworld"
    requiredLevels:
      - "Title.MASTER_BUILDER" # Title has no "minimum", so this will have to be their title
    noEdit: "&cYou can't edit this world!"
    gameRules:
      - "doWeatherCycle;false"
      - "doDaylightCycle;false"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1

# Additional logging for debugging
debug: false