# Plex Configuration File

server:
  test: "test string"

data:
  central:
    storage: sqlite # use mariadb, mongodb, or sqlite here
    user: ""
    password: ""
    hostname: 127.0.0.1
    port: 27017
    db: "plex"
  side: # This is redis, leave password blank if auth is false
    auth: true
    hostname: 127.0.0.1
    port: 6379
    password: ""