# Plex Configuration File
# For documentation, please visit: https://docs.plex.us.org

server:
  name: "Plexus"
  motd: "%servername% - Minecraft %mcversion%"
  colorize_motd: true
  sample:
    - "&cForums: https://forum.plex.us.org"

titles:
  masterbuilders: []
  owners: []

# Ban message is customized in the messages.yml file. The URL to appeal at is below.
banning:
  ban_url: "https://forum.plex.us.org"


# Settings for commands relating to Plex
commands:
  # Should Plex use a "true op" system with ranks or only permission nodes
  permissions: ranks

data:
  central:
    storage: sqlite # Use mariadb, mongodb, or sqlite here
    user: ""
    password: ""
    hostname: 127.0.0.1
    port: 27017
    db: "plex"
  side: # This is Redis, leave password blank if auth is false
    enabled: false
    auth: true
    hostname: 127.0.0.1
    port: 6379
    password: ""

# requiredLevel if permissions are ranks, else permissions
worlds:
  flatlands:
    name: "Flatlands"
    permission: "plex.world.flatlands"
    noEdit: "&cYou can't edit this world!"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1
  adminworld:
    name: "Admin World"
    permission: "plex.world.adminworld"
    requiredLevels:
      - "Rank.ADMIN" # Minimum rank requirement
    noEdit: "&cYou can't edit this world!"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1
  masterbuilderworld:
    name: "MasterBuilder World"
    permission: "plex.world.masterbuilderworld"
    requiredLevels:
      - "Title.MASTER_BUILDER" # Title has no "minimum", so this will have to be their title
    noEdit: "&cYou can't edit this world!"
    parameters:
      grass_block: 1
      dirt: 32
      stone: 16
      bedrock: 1

# Additional logging for debugging
debug: false